# Überführen heruntergeladener Wetterdaten in verständliche Darstellung

## Herunterladen von Tagesdaten

>go-dwd -limit=1 -resolution=daily -search=fuhlsbüttel -download

oder

>go-dwd -resolution=daily -stationID=1975 -download

erzeugt `dwd_daily_01975.csv.gz`

In [1]:
import pandas as pd

df = pd.read_csv("dwd_daily_01975.csv.gz")
df.messdatum = pd.to_datetime(df.messdatum)
df

,station_id,messdatum,kl__QN_3,kl__FX,kl__FM,kl__QN_4,kl__RSK,kl__RSKF,kl__SDK,kl__SHK_TAG,...,weather_phenomena__QN_4,weather_phenomena__NEBEL,weather_phenomena__GEWITTER,weather_phenomena__STURM_6,weather_phenomena__STURM_8,weather_phenomena__TAU,weather_phenomena__GLATTEIS,weather_phenomena__REIF,weather_phenomena__GRAUPEL,weather_phenomena__HAGEL
0,1975,1936-01-01,NaN,NaN,NaN,5,0.1,1,NaN,0.0,...,5,0,0,0,0,0,0,0,0,0
1,1975,1936-01-02,NaN,NaN,NaN,5,3.5,1,NaN,0.0,...,5,0,0,0,0,0,0,0,0,0
2,1975,1936-01-03,NaN,NaN,NaN,5,0.8,1,NaN,0.0,...,5,0,0,0,0,0,0,0,0,0
3,1975,1936-01-04,NaN,NaN,NaN,5,0.7,1,NaN,0.0,...,5,0,0,0,0,0,0,0,0,0
4,1975,1936-01-05,NaN,NaN,NaN,5,0.0,1,NaN,0.0,...,5,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30883,1975,2020-07-21,1.0,11.7,3.1,1,1.3,6,7.700,0.0,...,1,0,0,0,0,1,0,0,0,0
30884,1975,2020-07-22,1.0,9.8,2.5,1,0.0,6,6.117,0.0,...,1,0,0,0,0,1,0,0,0,0
30885,1975,2020-07-23,1.0,9.6,2.2,1,0.0,6,7.567,0.0,...,1,0,0,0,0,1,0,0,0,0
30886,1975,2020-07-24,1.0,12.7,4.1,1,0.6,6,5.917,0.0,...,1,0,0,0,0,1,0,0,0,0
30887,1975,2020-07-25,1.0,10.6,3.8,1,5.1,6,4.617,0.0,...,1,0,0,0,0,1,0,0,0,0

## Auflistung aller Spaltennamen

In [2]:
list(zip(list(df.columns), list(df.dtypes)))

[('station_id', dtype('int64')),
 ('messdatum', dtype('<M8[ns]')),
 ('kl__QN_3', dtype('float64')),
 ('kl__FX', dtype('float64')),
 ('kl__FM', dtype('float64')),
 ('kl__QN_4', dtype('int64')),
 ('kl__RSK', dtype('float64')),
 ('kl__RSKF', dtype('int64')),
 ('kl__SDK', dtype('float64')),
 ('kl__SHK_TAG', dtype('float64')),
 ('kl__NM', dtype('float64')),
 ('kl__VPM', dtype('float64')),
 ('kl__PM', dtype('float64')),
 ('kl__TMK', dtype('float64')),
 ('kl__UPM', dtype('float64')),
 ('kl__TXK', dtype('float64')),
 ('kl__TNK', dtype('float64')),
 ('kl__TGK', dtype('float64')),
 ('more_precip__QN_6', dtype('int64')),
 ('more_precip__RS', dtype('float64')),
 ('more_precip__RSF', dtype('int64')),
 ('more_precip__SH_TAG', dtype('float64')),
 ('more_precip__NSH_TAG', dtype('float64')),
 ('soil_temperature__QN_2', dtype('float64')),
 ('soil_temperature__V_TE002M', dtype('float64')),
 ('soil_temperature__V_TE005M', dtype('float64')),
 ('soil_temperature__V_TE010M', dtype('float64')),
 ('soil_temperature__V_TE020M', dtype('float64')),
 ('soil_temperature__V_TE050M', dtype('float64')),
 ('solar__QN_592', dtype('float64')),
 ('solar__ATMO_STRAHL', dtype('float64')),
 ('solar__FD_STRAHL', dtype('float64')),
 ('solar__FG_STRAHL', dtype('float64')),
 ('solar__SD_STRAHL', dtype('float64')),
 ('water_equiv__QN_6', dtype('float64')),
 ('water_equiv__ASH_6', dtype('float64')),
 ('water_equiv__SH_TAG', dtype('float64')),
 ('water_equiv__WASH_6', dtype('float64')),
 ('water_equiv__WAAS_6', dtype('float64')),
 ('weather_phenomena__QN_4', dtype('int64')),
 ('weather_phenomena__NEBEL', dtype('int64')),
 ('weather_phenomena__GEWITTER', dtype('int64')),
 ('weather_phenomena__STURM_6', dtype('int64')),
 ('weather_phenomena__STURM_8', dtype('int64')),
 ('weather_phenomena__TAU', dtype('int64')),
 ('weather_phenomena__GLATTEIS', dtype('int64')),
 ('weather_phenomena__REIF', dtype('int64')),
 ('weather_phenomena__GRAUPEL', dtype('int64')),
 ('weather_phenomena__HAGEL', dtype('int64'))]

## Erzeugung einer neuen Tabelle mit entsprechenden Bezeichnungen

In [3]:
df2 = df[["station_id", "messdatum"]].copy()
df2["atmosphärische_gegenstrahlung_tagessumme_in_jcm2"] = df.solar__ATMO_STRAHL
df2["dampfdruck_tagesmittel_in_hpa"] = df.kl__VPM
df2["diffuse_solare_strahlung_tagessumme_in_jcm2"] = df.solar__FD_STRAHL
df2["erdbodentemperatur_in_2cm_tiefe_in_grad_c"] = df.soil_temperature__V_TE002M
df2["erdbodentemperatur_in_5cm_tiefe_in_grad_c"] = df.soil_temperature__V_TE005M
df2["erdbodentemperatur_in_10cm_tiefe_in_grad_c"] = df.soil_temperature__V_TE010M
df2["erdbodentemperatur_in_20cm_tiefe_in_grad_c"] = df.soil_temperature__V_TE020M
df2["erdbodentemperatur_in_50cm_tiefe_in_grad_c"] = df.soil_temperature__V_TE050M
df2["globalstrahlung_tagessumme_in_jcm2"] = df.solar__FG_STRAHL
df2["luftdruck_stationshöhe_in_hpa"] = df.kl__PM
df2["luftfeuchtigkeit_tagesmittel_in_prozent"] = df.kl__UPM
df2["lufttemperatur_tagesminimum_in_2m_höhe_in_grad_c"] = df.kl__TNK
df2["lufttemperatur_tagesminimum_in_5cm_höhe_in_grad_c"] = df.kl__TGK
df2["lufttemperatur_tagesmittel_in_grad_c"] = df.kl__TMK
df2["lufttemperatur_tagesmaximum_in_2m_höhe_in_grad_c"] = df.kl__TXK
df2["neuschneehöhe_in_cm"] = df.more_precip__NSH_TAG
df2["niederschlagsform"] = df.more_precip__RSF.fillna(df.kl__RSKF)
df2["niederschlagshöhe_in_mm"] = df.more_precip__RS.fillna(df.kl__RSK)
df2["schneehöhe_in_cm"] = df.water_equiv__SH_TAG.fillna(df.kl__SHK_TAG).fillna(df.more_precip__SH_TAG).fillna(0).astype("uint")
df2["schneehöhe_ausgestochen_in_cm"] = df.water_equiv__ASH_6
df2["sonnenscheindauer_in_stunden"] = df.kl__SDK.fillna(df.solar__SD_STRAHL)
df2["wasseräquivalent_ausgestochene_schneehöhe_in_mm"] = df.water_equiv__WAAS_6
df2["wasseräquivalent_gesamte_schneehöhe_in_mm"] = df.water_equiv__WASH_6
df2["wetterereignis_gewitter"] = df.weather_phenomena__GEWITTER.fillna(0).astype("bool")
df2["wetterereignis_glatteis"] = df.weather_phenomena__GLATTEIS.fillna(0).astype("bool")
df2["wetterereignis_graupel"] = df.weather_phenomena__GRAUPEL.fillna(0).astype("bool")
df2["wetterereignis_hagel"] = df.weather_phenomena__HAGEL.fillna(0).astype("bool")
df2["wetterereignis_nebel"] = df.weather_phenomena__NEBEL.fillna(0).astype("bool")
df2["wetterereignis_sturm_min_6bft"] = df.weather_phenomena__STURM_6.fillna(0).astype("bool")
df2["wetterereignis_sturm_min_8bft"] = df.weather_phenomena__STURM_8.fillna(0).astype("bool")
df2["wetterereignis_reif"] = df.weather_phenomena__REIF.fillna(0).astype("bool")
df2["wetterereignis_tau"] = df.weather_phenomena__TAU.fillna(0).astype("bool")
df2["windgeschwindigkeit_in_metern_sekunde"] = df.kl__FM
df2["windspitze_in_metern_sekunde"] = df.kl__FX
df2["wolkenbedeckungsgrad_in_achteln"] = df.kl__NM
df2

,station_id,messdatum,atmosphärische_gegenstrahlung_tagessumme_in_jcm2,dampfdruck_tagesmittel_in_hpa,diffuse_solare_strahlung_tagessumme_in_jcm2,erdbodentemperatur_in_2cm_tiefe_in_grad_c,erdbodentemperatur_in_5cm_tiefe_in_grad_c,erdbodentemperatur_in_10cm_tiefe_in_grad_c,erdbodentemperatur_in_20cm_tiefe_in_grad_c,erdbodentemperatur_in_50cm_tiefe_in_grad_c,...,wetterereignis_graupel,wetterereignis_hagel,wetterereignis_nebel,wetterereignis_sturm_min_6bft,wetterereignis_sturm_min_8bft,wetterereignis_reif,wetterereignis_tau,windgeschwindigkeit_in_metern_sekunde,windspitze_in_metern_sekunde,wolkenbedeckungsgrad_in_achteln
0,1975,1936-01-01,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,NaN,7.7
1,1975,1936-01-02,NaN,8.1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,NaN,7.0
2,1975,1936-01-03,NaN,8.1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,NaN,8.0
3,1975,1936-01-04,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,NaN,7.7
4,1975,1936-01-05,NaN,6.8,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,NaN,3.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30883,1975,2020-07-21,NaN,11.9,NaN,NaN,18.3,18.6,19.0,18.8,...,False,False,False,False,False,False,True,3.1,11.7,3.2
30884,1975,2020-07-22,NaN,11.5,NaN,NaN,18.9,18.6,18.4,17.9,...,False,False,False,False,False,False,True,2.5,9.8,5.5
30885,1975,2020-07-23,NaN,11.9,NaN,NaN,21.0,20.2,19.4,18.0,...,False,False,False,False,False,False,True,2.2,9.6,6.3
30886,1975,2020-07-24,NaN,14.7,NaN,NaN,20.9,20.5,19.9,18.5,...,False,False,False,False,False,False,True,4.1,12.7,5.3
30887,1975,2020-07-25,NaN,16.0,NaN,NaN,20.7,20.3,19.7,18.5,...,False,False,False,False,False,False,True,3.8,10.6,6.1

## Speichern der neuen Tabelle als komprimierte CSV-Datei

In [4]:
station_id = df2.station_id.iloc[0]
df2.to_csv(f"dwd_tagesdaten_{station_id:05d}.csv.gz", index=False, date_format="%Y-%m-%d %H:%M:%S", float_format="%.3f")